/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author asuna
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public HomePage() {
        
        try {
            for(UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()){
                if("Windows Clasic".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex){
            ex.getMessage();
        }
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_Btn = new javax.swing.JLabel();
        Tentang_Btn = new javax.swing.JLabel();
        Kontak_Btn = new javax.swing.JLabel();
        Belanja_Btn = new javax.swing.JLabel();
        Home_Btn_eft2 = new javax.swing.JLabel();
        Home_Btn = new javax.swing.JLabel();
        Wishlist_Btn = new javax.swing.JLabel();
        Chart_Btn = new javax.swing.JLabel();
        Telusuri_Produk_Label = new javax.swing.JLabel();
        User_Btn = new javax.swing.JLabel();
        Cari_Item_TextField = new javax.swing.JTextField();
        Search_Bar_Label = new javax.swing.JLabel();
        Main_Panel = new javax.swing.JPanel();
        Home_Panel = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Belanja_Btn1 = new javax.swing.JLabel();
        Nama_Lengkap_Label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        Masukkan_Pesan_Label = new javax.swing.JLabel();
        Selengkapnya_Btn = new javax.swing.JLabel();
        Kirim_Pesan_Btn = new javax.swing.JLabel();
        Message_TextField = new javax.swing.JTextField();
        Email_TextField = new javax.swing.JTextField();
        Fullname_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Belanja_Panel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ProdukA_Label = new javax.swing.JLabel();
        ProdukB_Label1 = new javax.swing.JLabel();
        ProdukC_Label = new javax.swing.JLabel();
        Souvenir_Label = new javax.swing.JLabel();
        Merchandise_Label3 = new javax.swing.JLabel();
        Dekorasi_Label = new javax.swing.JLabel();
        Parsel_Label = new javax.swing.JLabel();
        Merchandise_Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Produk3_Label = new javax.swing.JLabel();
        Produk2_Label = new javax.swing.JLabel();
        Produk1_Label = new javax.swing.JLabel();
        TokoC_Label = new javax.swing.JLabel();
        TokoB_Label = new javax.swing.JLabel();
        TokoA_Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Kontak_Panel = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        About_Us_Panel = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        UserPagePanel = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        Instagram_Klik = new javax.swing.JLabel();
        Twitter_Klik = new javax.swing.JLabel();
        Facebook_Klik = new javax.swing.JLabel();
        GantiFoto_Tombol = new javax.swing.JLabel();
        Profile_Image = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 58, 148));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Search_Btn.png"))); // NOI18N
        Search_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Search_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Search_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Search_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Search_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1207, 45, -1, -1));

        Tentang_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Tentang.png"))); // NOI18N
        Tentang_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tentang_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tentang_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tentang_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tentang_BtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tentang_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Tentang_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1093, 128, -1, -1));

        Kontak_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Kontak.png"))); // NOI18N
        Kontak_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kontak_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kontak_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Kontak_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Kontak_BtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kontak_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Kontak_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 128, -1, -1));

        Belanja_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Belanja.png"))); // NOI18N
        Belanja_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Belanja_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Belanja_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Belanja_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Belanja_BtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Belanja_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Belanja_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 128, -1, -1));

        Home_Btn_eft2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Rumah effect 2.png"))); // NOI18N
        getContentPane().add(Home_Btn_eft2, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 128, -1, -1));

        Home_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Rumah.png"))); // NOI18N
        Home_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home_BtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Home_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Home_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 128, -1, -1));

        Wishlist_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/ic_baseline-favorite-border.png"))); // NOI18N
        Wishlist_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Wishlist_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Wishlist_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Wishlist_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Wishlist_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Wishlist_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Wishlist_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Wishlist_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 55, -1, -1));

        Chart_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/clarity_shopping-cart-line.png"))); // NOI18N
        Chart_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chart_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chart_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Chart_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Chart_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Chart_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Chart_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(Chart_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1338, 55, -1, -1));

        Telusuri_Produk_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Telusuri produk.png"))); // NOI18N
        getContentPane().add(Telusuri_Produk_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        User_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/carbon_user-avatar-filled-alt.png"))); // NOI18N
        User_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                User_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                User_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                User_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                User_BtnMouseReleased(evt);
            }
        });
        getContentPane().add(User_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1663, 51, -1, -1));

        Cari_Item_TextField.setBackground(new java.awt.Color(235, 239, 246));
        Cari_Item_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Cari_Item_TextField.setForeground(new java.awt.Color(102, 102, 102));
        Cari_Item_TextField.setBorder(null);
        Cari_Item_TextField.setCaretColor(new java.awt.Color(102, 102, 102));
        Cari_Item_TextField.setOpaque(false);
        Cari_Item_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Cari_Item_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Cari_Item_TextFieldFocusLost(evt);
            }
        });
        getContentPane().add(Cari_Item_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 66, 500, 30));

        Search_Bar_Label.setBackground(new java.awt.Color(55, 65, 168));
        Search_Bar_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Search Bar.png"))); // NOI18N
        getContentPane().add(Search_Bar_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, -1));

        Main_Panel.setLayout(new java.awt.CardLayout());

        Home_Panel.setBorder(null);
        Home_Panel.setAutoscrolls(true);
        Home_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Home_Panel.setEnabled(false);
        Home_Panel.setOpaque(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Belanja_Btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Masuk.png"))); // NOI18N
        Belanja_Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Belanja_Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Belanja_Btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Belanja_Btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Belanja_Btn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Belanja_Btn1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Belanja_Btn1MouseReleased(evt);
            }
        });
        jPanel2.add(Belanja_Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, -1));

        Nama_Lengkap_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Nama Lengkap.png"))); // NOI18N
        jPanel2.add(Nama_Lengkap_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 3340, -1, -1));

        Email_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Email.png"))); // NOI18N
        jPanel2.add(Email_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 3450, -1, -1));

        Masukkan_Pesan_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Masukkan pesan.png"))); // NOI18N
        jPanel2.add(Masukkan_Pesan_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 3550, -1, -1));

        Selengkapnya_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/selengkapnya_Btn.png"))); // NOI18N
        Selengkapnya_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Selengkapnya_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Selengkapnya_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Selengkapnya_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Selengkapnya_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selengkapnya_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Selengkapnya_BtnMouseReleased(evt);
            }
        });
        jPanel2.add(Selengkapnya_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 2660, -1, -1));

        Kirim_Pesan_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Kirim Pesan.png"))); // NOI18N
        Kirim_Pesan_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kirim_Pesan_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kirim_Pesan_BtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Kirim_Pesan_BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Kirim_Pesan_BtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Kirim_Pesan_BtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Kirim_Pesan_BtnMouseReleased(evt);
            }
        });
        jPanel2.add(Kirim_Pesan_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 3760, -1, -1));

        Message_TextField.setBackground(new java.awt.Color(220, 139, 27));
        Message_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Message_TextField.setForeground(new java.awt.Color(255, 255, 255));
        Message_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Message_TextField.setBorder(null);
        Message_TextField.setCaretColor(new java.awt.Color(255, 255, 255));
        Message_TextField.setOpaque(false);
        Message_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Message_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Message_TextFieldFocusLost(evt);
            }
        });
        Message_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Message_TextFieldActionPerformed(evt);
            }
        });
        Message_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Message_TextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(Message_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 3540, 420, 150));

        Email_TextField.setBackground(new java.awt.Color(220, 139, 27));
        Email_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Email_TextField.setForeground(new java.awt.Color(255, 255, 255));
        Email_TextField.setBorder(null);
        Email_TextField.setCaretColor(new java.awt.Color(255, 255, 255));
        Email_TextField.setOpaque(false);
        Email_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_TextFieldFocusLost(evt);
            }
        });
        Email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextFieldActionPerformed(evt);
            }
        });
        Email_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Email_TextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 3444, 400, -1));

        Fullname_TextField.setBackground(new java.awt.Color(220, 139, 27));
        Fullname_TextField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Fullname_TextField.setForeground(new java.awt.Color(255, 255, 255));
        Fullname_TextField.setBorder(null);
        Fullname_TextField.setCaretColor(new java.awt.Color(255, 255, 255));
        Fullname_TextField.setOpaque(false);
        Fullname_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Fullname_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Fullname_TextFieldFocusLost(evt);
            }
        });
        Fullname_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fullname_TextFieldActionPerformed(evt);
            }
        });
        Fullname_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Fullname_TextFieldKeyPressed(evt);
            }
        });
        jPanel2.add(Fullname_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 3334, 400, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Home Page/Home Page.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Home_Panel.setViewportView(jPanel2);

        Main_Panel.add(Home_Panel, "card2");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProdukA_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Produk A.png"))); // NOI18N
        jPanel1.add(ProdukA_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, -1, 522));

        ProdukB_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Produk C.png"))); // NOI18N
        jPanel1.add(ProdukB_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 1352, -1, -1));

        ProdukC_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Produk B.png"))); // NOI18N
        jPanel1.add(ProdukC_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1352, -1, -1));

        Souvenir_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Souvernir.png"))); // NOI18N
        jPanel1.add(Souvenir_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1913, -1, 1080));

        Merchandise_Label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Kado.png"))); // NOI18N
        jPanel1.add(Merchandise_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 2453, -1, -1));

        Dekorasi_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Dekorasi Hari Raya.png"))); // NOI18N
        jPanel1.add(Dekorasi_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 2453, -1, -1));

        Parsel_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Parcel.png"))); // NOI18N
        jPanel1.add(Parsel_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 1913, -1, -1));

        Merchandise_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Merchantdise.png"))); // NOI18N
        jPanel1.add(Merchandise_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1913, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/ic_baseline-navigate-next.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 3700, -1, -1));

        Produk3_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Produk 3.png"))); // NOI18N
        jPanel1.add(Produk3_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 3532, -1, -1));

        Produk2_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Produk 2.png"))); // NOI18N
        jPanel1.add(Produk2_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 3532, -1, -1));

        Produk1_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Produk 1.png"))); // NOI18N
        jPanel1.add(Produk1_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3532, -1, -1));

        TokoC_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Toko 3.png"))); // NOI18N
        jPanel1.add(TokoC_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 2993, -1, -1));

        TokoB_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Toko 2.png"))); // NOI18N
        jPanel1.add(TokoB_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 2993, -1, -1));

        TokoA_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Toko 1.png"))); // NOI18N
        jPanel1.add(TokoA_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2993, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/ic_baseline-navigate-next.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 3120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Shop Page/Shop_Page.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Belanja_Panel.setViewportView(jPanel1);

        Main_Panel.add(Belanja_Panel, "card3");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Contact Page/Contact Page.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Kontak_Panel.setViewportView(jPanel3);

        Main_Panel.add(Kontak_Panel, "card4");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/About Us Page/About Us Page.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        About_Us_Panel.setViewportView(jPanel4);

        Main_Panel.add(About_Us_Panel, "card5");

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Instagram_Klik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Instagram Btn.png"))); // NOI18N
        Instagram_Klik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Instagram_KlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Instagram_KlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Instagram_KlikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Instagram_KlikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Instagram_KlikMouseReleased(evt);
            }
        });
        jPanel5.add(Instagram_Klik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        Twitter_Klik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Twitter Btn.png"))); // NOI18N
        Twitter_Klik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Twitter_KlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Twitter_KlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Twitter_KlikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Twitter_KlikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Twitter_KlikMouseReleased(evt);
            }
        });
        jPanel5.add(Twitter_Klik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 405, -1, -1));

        Facebook_Klik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Facebook Btn.png"))); // NOI18N
        Facebook_Klik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Facebook_KlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Facebook_KlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Facebook_KlikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Facebook_KlikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Facebook_KlikMouseReleased(evt);
            }
        });
        jPanel5.add(Facebook_Klik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        GantiFoto_Tombol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Effect/Ganti Foto Btn.png"))); // NOI18N
        GantiFoto_Tombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GantiFoto_TombolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GantiFoto_TombolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GantiFoto_TombolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GantiFoto_TombolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GantiFoto_TombolMouseReleased(evt);
            }
        });
        jPanel5.add(GantiFoto_Tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 494, -1, -1));

        Profile_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/User Page/Profile.png"))); // NOI18N
        jPanel5.add(Profile_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1227, 1050, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/User Page/User Page.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        UserPagePanel.setViewportView(jPanel5);

        Main_Panel.add(UserPagePanel, "card6");

        getContentPane().add(Main_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1920, 890));

        setBounds(0, 0, 1941, 1136);
    }// </editor-fold>//GEN-END:initComponents

    private void Fullname_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fullname_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fullname_TextFieldActionPerformed

    private void Email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextFieldActionPerformed

    private void Message_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Message_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Message_TextFieldActionPerformed

    private void Search_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_BtnMouseClicked
        // TODO add your handling code here:
            ImageIcon Btn_Search;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Search = new ImageIcon("src/Picture/Effect/Search_Btn effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Search_Btn.setIcon(Btn_Search);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Search_BtnMouseClicked

    private void Search_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Search;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Search = new ImageIcon("src/Picture/Effect/Search_Btn effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Search_Btn.setIcon(Btn_Search);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Search_BtnMouseEntered

    private void Search_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_BtnMouseExited
        // TODO add your handling code here:
        ImageIcon Btn_Search;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Search = new ImageIcon("src/Picture/Effect/Search_Btn.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Search_Btn.setIcon(Btn_Search);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Search_BtnMouseExited

    private void Search_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Search;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Search = new ImageIcon("src/Picture/Effect/Search_Btn effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Search_Btn.setIcon(Btn_Search);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Search_BtnMousePressed

    private void Search_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Search;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Search = new ImageIcon("src/Picture/Effect/Search_Btn.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Search_Btn.setIcon(Btn_Search);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Search_BtnMouseReleased

    private void Chart_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chart_BtnMouseClicked
        // TODO add your handling code here:
         ImageIcon Btn_Chart;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Chart = new ImageIcon("src/Picture/Effect/clarity_shopping-cart-line effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Chart_Btn.setIcon(Btn_Chart);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Chart_BtnMouseClicked

    private void Chart_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chart_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Chart;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Chart = new ImageIcon("src/Picture/Effect/clarity_shopping-cart-line effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Chart_Btn.setIcon(Btn_Chart);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Chart_BtnMouseEntered

    private void Chart_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chart_BtnMouseExited
            ImageIcon Btn_Chart;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Chart = new ImageIcon("src/Picture/Effect/clarity_shopping-cart-line.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Chart_Btn.setIcon(Btn_Chart);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Chart_BtnMouseExited

    private void Chart_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chart_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Chart;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Chart = new ImageIcon("src/Picture/Effect/clarity_shopping-cart-line effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Chart_Btn.setIcon(Btn_Chart);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Chart_BtnMousePressed

    private void Chart_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chart_BtnMouseReleased
        // TODO add your handling code here:
            ImageIcon Btn_Chart;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Chart = new ImageIcon("src/Picture/Effect/clarity_shopping-cart-line.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Chart_Btn.setIcon(Btn_Chart);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Chart_BtnMouseReleased

    private void Wishlist_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wishlist_BtnMouseClicked
        // TODO add your handling code here:
        ImageIcon Btn_Wishlist;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Wishlist = new ImageIcon("src/Picture/Effect/ic_baseline-favorite-border effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Wishlist_Btn.setIcon(Btn_Wishlist);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Wishlist_BtnMouseClicked

    private void Wishlist_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wishlist_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Wishlist;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Wishlist = new ImageIcon("src/Picture/Effect/ic_baseline-favorite-border effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Wishlist_Btn.setIcon(Btn_Wishlist);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Wishlist_BtnMouseEntered

    private void Wishlist_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wishlist_BtnMouseExited
        // TODO add your handling code here:
            ImageIcon Btn_Wishlist;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Wishlist = new ImageIcon("src/Picture/Effect/ic_baseline-favorite-border.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Wishlist_Btn.setIcon(Btn_Wishlist);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Wishlist_BtnMouseExited

    private void Wishlist_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wishlist_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Wishlist;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Wishlist = new ImageIcon("src/Picture/Effect/ic_baseline-favorite-border effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Wishlist_Btn.setIcon(Btn_Wishlist);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Wishlist_BtnMousePressed

    private void Wishlist_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wishlist_BtnMouseReleased
        // TODO add your handling code here
        ImageIcon Btn_Wishlist;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Wishlist = new ImageIcon("src/Picture/Effect/ic_baseline-favorite-border.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Wishlist_Btn.setIcon(Btn_Wishlist);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Wishlist_BtnMouseReleased

    private void User_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_BtnMouseClicked
        // TODO add your handling code here:
         ImageIcon Btn_User;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_User = new ImageIcon("src/Picture/Effect/carbon_user-avatar-filled-alt effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            User_Btn.setIcon(Btn_User);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(UserPagePanel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
    }//GEN-LAST:event_User_BtnMouseClicked

    private void User_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_User;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_User = new ImageIcon("src/Picture/Effect/carbon_user-avatar-filled-alt effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            User_Btn.setIcon(Btn_User);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_User_BtnMouseEntered

    private void User_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_BtnMouseExited
        // TODO add your handling code here:
        ImageIcon Btn_User;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_User = new ImageIcon("src/Picture/Effect/carbon_user-avatar-filled-alt.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            User_Btn.setIcon(Btn_User);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_User_BtnMouseExited

    private void User_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_User;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_User = new ImageIcon("src/Picture/Effect/carbon_user-avatar-filled-alt effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            User_Btn.setIcon(Btn_User);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_User_BtnMousePressed

    private void User_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_BtnMouseReleased
        // TODO add your handling code here:
         ImageIcon Btn_User;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_User = new ImageIcon("src/Picture/Effect/carbon_user-avatar-filled-alt.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            User_Btn.setIcon(Btn_User);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_User_BtnMouseReleased

    private void Home_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_BtnMouseClicked
        // TODO add your handling code here:
        ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
        
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

 
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(Home_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
           
    }//GEN-LAST:event_Home_BtnMouseClicked

    private void Home_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_BtnMouseEntered
        // TODO add your handling code here:
            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
             ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

 
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Home_BtnMouseEntered

    private void Home_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_BtnMouseExited
        // TODO add your handling code here:
        //ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            //Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            //Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Home_BtnMouseExited

    private void Home_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Home_BtnMouseReleased

    private void Belanja_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_BtnMouseClicked
        // TODO add your handling code here:
        Home_Btn_eft2.setVisible(false);
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
        
            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

 
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
        //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(Belanja_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
    }//GEN-LAST:event_Belanja_BtnMouseClicked

    private void Belanja_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_BtnMouseEntered
        // TODO add your handling code here:
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

 
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_BtnMouseEntered

    private void Belanja_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_BtnMouseExited
        // TODO add your handling code here:
       // ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
           // untuk memanggil ImageIcon*/
            //Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            //Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_BtnMouseExited

    private void Belanja_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_BtnMouseReleased
        ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_BtnMouseReleased

    private void Kontak_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kontak_BtnMouseClicked
        // TODO add your handling code here:
        Home_Btn_eft2.setVisible(false);
        ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
        
       
             ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
            
            //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(Kontak_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();

    }//GEN-LAST:event_Kontak_BtnMouseClicked

    private void Kontak_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kontak_BtnMouseEntered
        // TODO add your handling code here:
            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kontak_BtnMouseEntered

    private void Kontak_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kontak_BtnMouseExited
        // TODO add your handling code here:
        //ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            //Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            //Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kontak_BtnMouseExited

    private void Kontak_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kontak_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kontak_BtnMouseReleased

    private void Tentang_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tentang_BtnMouseClicked
        // TODO add your handling code here:
        Home_Btn_eft2.setVisible(false);
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
        
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
            
            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(About_Us_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
    }//GEN-LAST:event_Tentang_BtnMouseClicked

    private void Tentang_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tentang_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
        ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Belanja.png");/*Format pemanggilan file ImageIcon 
           // yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/

            ImageIcon Btn_Kontak;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Kontak = new ImageIcon("src/Picture/Effect/Kontak.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kontak_Btn.setIcon(Btn_Kontak);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
            
            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Tentang_BtnMouseEntered

    private void Tentang_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tentang_BtnMouseExited
        // TODO add your handling code here:
        //ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            //Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            //Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Tentang_BtnMouseExited

    private void Tentang_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tentang_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            //untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang.png");/*Format pemanggilan file ImageIcon 
            //yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            //yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Tentang_BtnMouseReleased

    private void Belanja_Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_Btn1MouseClicked
        // TODO add your handling code here:
            ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Ayo Belanja effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn1.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
            //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(Belanja_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
         Home_Btn_eft2.setVisible(false);
            ImageIcon Btn_Belanja1;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja1 = new ImageIcon("src/Picture/Effect/Belanja effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn.setIcon(Btn_Belanja1);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_Btn1MouseClicked

    private void Belanja_Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_Btn1MouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Ayo Belanja effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn1.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_Btn1MouseEntered

    private void Belanja_Btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_Btn1MouseExited
        // TODO add your handling code here:
        ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Ayo Belanja.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn1.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_Btn1MouseExited

    private void Belanja_Btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_Btn1MousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Belanja;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Belanja = new ImageIcon("src/Picture/Effect/Ayo Belanja effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn1.setIcon(Btn_Belanja);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_Btn1MousePressed

    private void Belanja_Btn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Belanja_Btn1MouseReleased
        // TODO add your handling code here:
            ImageIcon Btn_KirimPesan;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_KirimPesan = new ImageIcon("src/Picture/Effect/Ayo Belanja.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Belanja_Btn1.setIcon(Btn_KirimPesan);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Belanja_Btn1MouseReleased

    private void Kirim_Pesan_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kirim_Pesan_BtnMouseClicked
        // TODO add your handling code here:
         ImageIcon Btn_KirimPesan;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_KirimPesan = new ImageIcon("src/Picture/Effect/Kirim Pesan effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kirim_Pesan_Btn.setIcon(Btn_KirimPesan);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kirim_Pesan_BtnMouseClicked

    private void Kirim_Pesan_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kirim_Pesan_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_KirimPesan;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_KirimPesan = new ImageIcon("src/Picture/Effect/Kirim Pesan effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kirim_Pesan_Btn.setIcon(Btn_KirimPesan);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kirim_Pesan_BtnMouseEntered

    private void Kirim_Pesan_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kirim_Pesan_BtnMouseExited
        // TODO add your handling code here:
            ImageIcon Btn_KirimPesan;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_KirimPesan = new ImageIcon("src/Picture/Effect/Kirim Pesan.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kirim_Pesan_Btn.setIcon(Btn_KirimPesan);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kirim_Pesan_BtnMouseExited

    private void Kirim_Pesan_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kirim_Pesan_BtnMousePressed
        // TODO add your handling code here:
         ImageIcon Btn_KirimPesan;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_KirimPesan = new ImageIcon("src/Picture/Effect/Kirim Pesan effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Kirim_Pesan_Btn.setIcon(Btn_KirimPesan);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Kirim_Pesan_BtnMousePressed

    private void Kirim_Pesan_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kirim_Pesan_BtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Kirim_Pesan_BtnMouseReleased

    private void Selengkapnya_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selengkapnya_BtnMouseClicked
        // TODO add your handling code here:
        ImageIcon Btn_Selengkapnya;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Selengkapnya = new ImageIcon("src/Picture/Effect/Selengkapnya_Btn effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Selengkapnya_Btn.setIcon(Btn_Selengkapnya);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            
        //Menghapus Panel   
        Main_Panel.removeAll();
        Main_Panel.repaint();
        Main_Panel.revalidate();
        
        //Menambah panel
        Main_Panel.add(About_Us_Panel);
        Main_Panel.repaint();
        Main_Panel.revalidate();
        Home_Btn_eft2.setVisible(false);
            ImageIcon Btn_Tentang;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Tentang = new ImageIcon("src/Picture/Effect/Tentang effect 2.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Tentang_Btn.setIcon(Btn_Tentang);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
            ImageIcon Btn_Home;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Home = new ImageIcon("src/Picture/Effect/Rumah.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Home_Btn.setIcon(Btn_Home);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
        
    }//GEN-LAST:event_Selengkapnya_BtnMouseClicked

    private void Selengkapnya_BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selengkapnya_BtnMouseEntered
        // TODO add your handling code here:
        ImageIcon Btn_Selengkapnya;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Selengkapnya = new ImageIcon("src/Picture/Effect/Selengkapnya_Btn effect 1.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Selengkapnya_Btn.setIcon(Btn_Selengkapnya);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Selengkapnya_BtnMouseEntered

    private void Selengkapnya_BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selengkapnya_BtnMouseExited
        // TODO add your handling code here:
            ImageIcon Btn_Selengkapnya;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Selengkapnya = new ImageIcon("src/Picture/Effect/Selengkapnya_Btn.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Selengkapnya_Btn.setIcon(Btn_Selengkapnya);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Selengkapnya_BtnMouseExited

    private void Selengkapnya_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selengkapnya_BtnMousePressed
        // TODO add your handling code here:
        ImageIcon Btn_Selengkapnya;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Selengkapnya = new ImageIcon("src/Picture/Effect/Selengkapnya_Btn effect 3.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Selengkapnya_Btn.setIcon(Btn_Selengkapnya);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Selengkapnya_BtnMousePressed

    private void Selengkapnya_BtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selengkapnya_BtnMouseReleased
        // TODO add your handling code here:
        ImageIcon Btn_Selengkapnya;/*Deklarasi variabel yang digunakan 
            untuk memanggil ImageIcon*/
            Btn_Selengkapnya = new ImageIcon("src/Picture/Effect/Selengkapnya_Btn.png");/*Format pemanggilan file ImageIcon 
            yang ingin dipanggil*/
            Selengkapnya_Btn.setIcon(Btn_Selengkapnya);/*Pallete pada java (berupa JLabel) 
            yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Selengkapnya_BtnMouseReleased

    private void Fullname_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Fullname_TextFieldFocusGained
        Nama_Lengkap_Label.setVisible(false); //JLabel dibuat menghilang
    }//GEN-LAST:event_Fullname_TextFieldFocusGained

    private void Fullname_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Fullname_TextFieldFocusLost
        // TODO add your handling code here:
        if(Fullname_TextField.getText().length() > 0){ // Ketika jumlah karakter lebih dari nol
            Nama_Lengkap_Label.setVisible(false);// Jlabel dibuat menghilang
        }else{
            Nama_Lengkap_Label.setVisible(true);// Jlabel dibuat muncul kembali
        }
    }//GEN-LAST:event_Fullname_TextFieldFocusLost

    private void Fullname_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fullname_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER){ // Kondisi apabila menggunakan tombol down atau tombol enter pada keyboard
            Email_TextField.requestFocus(); // Menuju JTextField yang berada dibawahnya
       }
    }//GEN-LAST:event_Fullname_TextFieldKeyPressed

    private void Email_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TextFieldFocusGained

            Email_Label.setVisible(false);// Jlabel dibuat menghilang
        
    }//GEN-LAST:event_Email_TextFieldFocusGained

    private void Email_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Email_TextFieldKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER){ // Kondisi apabila menggunakan tombol down atau tombol enter pada keyboard
            Message_TextField.requestFocus(); // Menuju JTextField yang berada dibawahnya
       }else if(evt.getKeyCode() == KeyEvent.VK_UP ){ // Kondisi apabila menggunakan tombol up pada keyboard
            Fullname_TextField.requestFocus(); // Menuju JTextField yang berada diatasnya
       }
    }//GEN-LAST:event_Email_TextFieldKeyPressed

    private void Email_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TextFieldFocusLost
        // TODO add your handling code here:
         if(Email_TextField.getText().length() > 0){ // Ketika jumlah karakter lebih dari nol
            Email_Label.setVisible(false);// Jlabel dibuat menghilang
        }else{
            Email_Label.setVisible(true);// Jlabel dibuat muncul kembali
        }
    }//GEN-LAST:event_Email_TextFieldFocusLost

    private void Message_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Message_TextFieldFocusGained
        Masukkan_Pesan_Label.setVisible(false);
    }//GEN-LAST:event_Message_TextFieldFocusGained

    private void Message_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Message_TextFieldFocusLost
         if(Message_TextField.getText().length() > 0){ // Ketika jumlah karakter lebih dari nol
            Masukkan_Pesan_Label.setVisible(false);// Jlabel dibuat menghilang
        }else{
            Masukkan_Pesan_Label.setVisible(true);// Jlabel dibuat muncul kembali
        }
    }//GEN-LAST:event_Message_TextFieldFocusLost

    private void Message_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Message_TextFieldKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_UP ){ // Kondisi apabila menggunakan tombol up pada keyboard
            Email_TextField.requestFocus(); // Menuju JTextField yang berada diatasnya
       }
    }//GEN-LAST:event_Message_TextFieldKeyPressed

    private void Cari_Item_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cari_Item_TextFieldFocusGained
        // TODO add your handling code here:
        Telusuri_Produk_Label.setVisible(false);//JLabel dibuat menghilang
    }//GEN-LAST:event_Cari_Item_TextFieldFocusGained

    private void Cari_Item_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cari_Item_TextFieldFocusLost
        // TODO add your handling code here:
        if(Cari_Item_TextField.getText().length() > 0){ // Ketika jumlah karakter lebih dari nol
            Telusuri_Produk_Label.setVisible(false);// Jlabel dibuat menghilang
        }else{
            Telusuri_Produk_Label.setVisible(true);// Jlabel dibuat muncul kembali
        }
    }//GEN-LAST:event_Cari_Item_TextFieldFocusLost

    private void GantiFoto_TombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GantiFoto_TombolMouseClicked
        ImageIcon GantiFotoTombol;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        GantiFotoTombol = new ImageIcon("src/Picture/Effect/Ganti Foto Btn Effect 2.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        GantiFoto_Tombol.setIcon(GantiFotoTombol);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_GantiFoto_TombolMouseClicked

    private void GantiFoto_TombolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GantiFoto_TombolMouseEntered
        ImageIcon GantiFotoTombol;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        GantiFotoTombol = new ImageIcon("src/Picture/Effect/Ganti Foto Btn Effect 1.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        GantiFoto_Tombol.setIcon(GantiFotoTombol);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_GantiFoto_TombolMouseEntered

    private void GantiFoto_TombolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GantiFoto_TombolMouseExited
        ImageIcon GantiFotoTombol;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        GantiFotoTombol = new ImageIcon("src/Picture/Effect/Ganti Foto Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        GantiFoto_Tombol.setIcon(GantiFotoTombol);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_GantiFoto_TombolMouseExited

    private void GantiFoto_TombolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GantiFoto_TombolMousePressed
        ImageIcon GantiFotoTombol;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        GantiFotoTombol = new ImageIcon("src/Picture/Effect/Ganti Foto Btn Effect 3.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        GantiFoto_Tombol.setIcon(GantiFotoTombol);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_GantiFoto_TombolMousePressed

    private void GantiFoto_TombolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GantiFoto_TombolMouseReleased
        ImageIcon GantiFotoTombol;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        GantiFotoTombol = new ImageIcon("src/Picture/Effect/Ganti Foto Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        GantiFoto_Tombol.setIcon(GantiFotoTombol);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_GantiFoto_TombolMouseReleased

    private void Twitter_KlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Twitter_KlikMouseClicked
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Twitter Btn Effect 2.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Twitter_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        Desktop d = Desktop.getDesktop();
        try {
            try {
                d.browse(new URI("https://twitter.com/jokowi"));
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Twitter_KlikMouseClicked

    private void Twitter_KlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Twitter_KlikMouseEntered
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Twitter Btn Effect 1.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Twitter_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Twitter_KlikMouseEntered

    private void Twitter_KlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Twitter_KlikMouseExited
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Twitter Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Twitter_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Twitter_KlikMouseExited

    private void Twitter_KlikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Twitter_KlikMousePressed
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Twitter Btn Effect 3.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Twitter_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Twitter_KlikMousePressed

    private void Twitter_KlikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Twitter_KlikMouseReleased
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Twitter Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Twitter_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Twitter_KlikMouseReleased

    private void Facebook_KlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Facebook_KlikMouseClicked
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Facebook Btn Effect 2.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Facebook_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        Desktop d = Desktop.getDesktop();
        try {
            try {
                d.browse(new URI("https://www.facebook.com/Jokowi"));
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Facebook_KlikMouseClicked

    private void Facebook_KlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Facebook_KlikMouseEntered
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Facebook Btn Effect 1.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Facebook_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Facebook_KlikMouseEntered

    private void Facebook_KlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Facebook_KlikMouseExited
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Facebook Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Facebook_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Facebook_KlikMouseExited

    private void Facebook_KlikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Facebook_KlikMousePressed
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Facebook Btn Effect 3.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Facebook_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Facebook_KlikMousePressed

    private void Facebook_KlikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Facebook_KlikMouseReleased
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Facebook Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Facebook_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Facebook_KlikMouseReleased

    private void Instagram_KlikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instagram_KlikMouseReleased
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Instagram Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Instagram_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Instagram_KlikMouseReleased

    private void Instagram_KlikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instagram_KlikMousePressed
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Instagram Btn Effect 3.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Instagram_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Instagram_KlikMousePressed

    private void Instagram_KlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instagram_KlikMouseExited
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Instagram Btn.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Instagram_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Instagram_KlikMouseExited

    private void Instagram_KlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instagram_KlikMouseEntered
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Instagram Btn Effect 1.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Instagram_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Instagram_KlikMouseEntered

    private void Instagram_KlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instagram_KlikMouseClicked
        ImageIcon MedsosKlik;/*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MedsosKlik = new ImageIcon("src/Picture/Effect/Instagram Btn Effect 2.png");/*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Instagram_Klik.setIcon(MedsosKlik);/*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        Desktop d = Desktop.getDesktop();
        try {
            try {
                d.browse(new URI("https://www.instagram.com/jokowi/"));
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Instagram_KlikMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane About_Us_Panel;
    private javax.swing.JLabel Belanja_Btn;
    private javax.swing.JLabel Belanja_Btn1;
    private javax.swing.JScrollPane Belanja_Panel;
    private javax.swing.JTextField Cari_Item_TextField;
    private javax.swing.JLabel Chart_Btn;
    private javax.swing.JLabel Dekorasi_Label;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JLabel Facebook_Klik;
    private javax.swing.JTextField Fullname_TextField;
    private javax.swing.JLabel GantiFoto_Tombol;
    private javax.swing.JLabel Home_Btn;
    private javax.swing.JLabel Home_Btn_eft2;
    private javax.swing.JScrollPane Home_Panel;
    private javax.swing.JLabel Instagram_Klik;
    private javax.swing.JLabel Kirim_Pesan_Btn;
    private javax.swing.JLabel Kontak_Btn;
    private javax.swing.JScrollPane Kontak_Panel;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JLabel Masukkan_Pesan_Label;
    private javax.swing.JLabel Merchandise_Label;
    private javax.swing.JLabel Merchandise_Label3;
    private javax.swing.JTextField Message_TextField;
    private javax.swing.JLabel Nama_Lengkap_Label;
    private javax.swing.JLabel Parsel_Label;
    private javax.swing.JLabel Produk1_Label;
    private javax.swing.JLabel Produk2_Label;
    private javax.swing.JLabel Produk3_Label;
    private javax.swing.JLabel ProdukA_Label;
    private javax.swing.JLabel ProdukB_Label1;
    private javax.swing.JLabel ProdukC_Label;
    private javax.swing.JLabel Profile_Image;
    private javax.swing.JLabel Search_Bar_Label;
    private javax.swing.JLabel Search_Btn;
    private javax.swing.JLabel Selengkapnya_Btn;
    private javax.swing.JLabel Souvenir_Label;
    private javax.swing.JLabel Telusuri_Produk_Label;
    private javax.swing.JLabel Tentang_Btn;
    private javax.swing.JLabel TokoA_Label;
    private javax.swing.JLabel TokoB_Label;
    private javax.swing.JLabel TokoC_Label;
    private javax.swing.JLabel Twitter_Klik;
    private javax.swing.JScrollPane UserPagePanel;
    private javax.swing.JLabel User_Btn;
    private javax.swing.JLabel Wishlist_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
