/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent; /*Fungsi import yang digunakan untuk proses deklarasi dari class event yang berisi komponen KeyEvent*/
import java.sql.Connection; /*Fungsi import interface yang menyediakan method untuk menghubungi database*/
import java.sql.DriverManager; /*Fungsi import yang menyediakan sebuah class yang mengelola driver*/
import java.sql.PreparedStatement; /*Fungsi import untuk eksekusi query SQL*/
import java.sql.ResultSet; /*Fungsi import interface untuk menampung data hasil query*/
import javax.swing.ImageIcon; /*Fungsi import yang menyediakan antarmuka berupa URL, nama file, atau array byte*/
import javax.swing.JFrame; /*Fungsi import yang menyediakan sarana pengolahan frame*/
import javax.swing.JOptionPane; /*Fungsi import yang memungkinkan user memperoleh tampilan sebuah dialog box sederhana berisikan suatu informasi*/

/**
 *
 * @author iwaya
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        NamaPenggunaEmail_TextField.setBackground(new java.awt.Color(0,0,0,1));
        KataSandi_TextField.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo_Picture = new javax.swing.JLabel();
        MataTutup_Icon = new javax.swing.JLabel();
        NamaPenggunaEmail_Text = new javax.swing.JLabel();
        NamaPenggunaEmail_TextField = new javax.swing.JTextField();
        NamaPenggunaEmail_Field = new javax.swing.JLabel();
        KataSandi_Text = new javax.swing.JLabel();
        KataSandi_TextField = new javax.swing.JPasswordField();
        KataSandi_Field = new javax.swing.JLabel();
        Masuk_Tombol = new javax.swing.JLabel();
        LupaKataSandi_Klik = new javax.swing.JLabel();
        Daftar_Klik = new javax.swing.JLabel();
        KeduanyaSalah_NotifFalse = new javax.swing.JLabel();
        Login_Picture = new javax.swing.JLabel();
        Latar_Picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 57, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Logo.png"))); // NOI18N
        jPanel1.add(Logo_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 95, -1, -1));

        MataTutup_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Mata Tutup.png"))); // NOI18N
        MataTutup_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MataTutup_IconMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MataTutup_IconMousePressed(evt);
            }
        });
        jPanel1.add(MataTutup_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1616, 540, -1, -1));

        NamaPenggunaEmail_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Nama Pengguna atau Email.png"))); // NOI18N
        jPanel1.add(NamaPenggunaEmail_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 415, -1, -1));

        NamaPenggunaEmail_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        NamaPenggunaEmail_TextField.setForeground(new java.awt.Color(255, 255, 255));
        NamaPenggunaEmail_TextField.setBorder(null);
        NamaPenggunaEmail_TextField.setOpaque(false);
        NamaPenggunaEmail_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NamaPenggunaEmail_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NamaPenggunaEmail_TextFieldFocusLost(evt);
            }
        });
        NamaPenggunaEmail_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaPenggunaEmail_TextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(NamaPenggunaEmail_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 410, 330, 30));

        NamaPenggunaEmail_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Nama Pengguna Email Field.png"))); // NOI18N
        jPanel1.add(NamaPenggunaEmail_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1234, 389, -1, -1));

        KataSandi_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Kata Sandi.png"))); // NOI18N
        jPanel1.add(KataSandi_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 545, -1, -1));

        KataSandi_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        KataSandi_TextField.setForeground(new java.awt.Color(255, 255, 255));
        KataSandi_TextField.setBorder(null);
        KataSandi_TextField.setEchoChar('\u25cf');
        KataSandi_TextField.setOpaque(false);
        KataSandi_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KataSandi_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KataSandi_TextFieldFocusLost(evt);
            }
        });
        KataSandi_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KataSandi_TextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(KataSandi_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 540, 300, 30));

        KataSandi_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Kata Sandi Field.png"))); // NOI18N
        jPanel1.add(KataSandi_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1234, 518, -1, -1));

        Masuk_Tombol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Tombol Masuk 1.png"))); // NOI18N
        Masuk_Tombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Masuk_TombolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Masuk_TombolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Masuk_TombolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Masuk_TombolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Masuk_TombolMouseReleased(evt);
            }
        });
        jPanel1.add(Masuk_Tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 652, -1, -1));

        LupaKataSandi_Klik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Lupa kata sandi 1.png"))); // NOI18N
        LupaKataSandi_Klik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LupaKataSandi_KlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LupaKataSandi_KlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LupaKataSandi_KlikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LupaKataSandi_KlikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LupaKataSandi_KlikMouseReleased(evt);
            }
        });
        jPanel1.add(LupaKataSandi_Klik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1249, 677, -1, -1));

        Daftar_Klik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Daftar 1.png"))); // NOI18N
        Daftar_Klik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Daftar_KlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Daftar_KlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Daftar_KlikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Daftar_KlikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Daftar_KlikMouseReleased(evt);
            }
        });
        jPanel1.add(Daftar_Klik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1525, 945, -1, -1));
        jPanel1.add(KeduanyaSalah_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1244, 608, -1, -1));

        Login_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Login.png"))); // NOI18N
        jPanel1.add(Login_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 0, -1, -1));

        Latar_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LoginPage/Gambar Latar.png"))); // NOI18N
        jPanel1.add(Latar_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 389, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Masuk_TombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_TombolMouseClicked
        ImageIcon MasukTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MasukTombol_icon = new ImageIcon("src/Pictures/LoginPage/Tombol Masuk 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Masuk_Tombol.setIcon(MasukTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        /*Deklarasi variabel untuk melakukan pemasukkan data pada mysql*/
        String NamaPengguna = NamaPenggunaEmail_TextField.getText(); /*Variabel untuk mengambil data Nama Pengguna*/
        String Email = NamaPenggunaEmail_TextField.getText(); /*Variabel untuk mengambil data Email*/
        String KataSandi = KataSandi_TextField.getPassword().toString(); /*Variabel untuk mengambil data Kata Sandi*/
        
        /*Try dan Catch digunakan untuk menangani error pada java, eksekusi yang menampilkan 
        error dan membuat program tetap berjalan tanpa dihentikan secara langsung*/
        try{ /*Statement yang digunakan untuk menghubungkan database pada mysql ke Netbeans*/
           Class.forName("com.mysql.jdbc.Driver"); /*Pemanggilan kelas pad library JDBC driver mysql*/
           Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coba","root", ""); /*variabel yang digunakan untuk pemanggilan driver mysql pada database server*/
           String sql = "select * from tb_daftar where (nama=? or email=?) and katasandi=?"; /*Syntax pada mysql yang digunakan untuk melakukan pemasukkan data username dan password*/
           PreparedStatement pst = connect.prepareStatement(sql); /*Variabel untuk mengambil data-data yang ingin dimasukkan ke dalam database server*/
           pst.setString(1, NamaPenggunaEmail_TextField.getText()); /*Pemasangan dan pemasukkan data username pada database server*/
           pst.setString(2, NamaPenggunaEmail_TextField.getText()); /*Pemasangan dan pemasukkan data email pada database server*/
           pst.setString(3, KataSandi_TextField.getText()); /*Pemasangan dan pemasukkan data password pada database server*/
           ResultSet rs = pst.executeQuery(); /*Memeriksa apakah ada hasil yang dimasukkan*/
           
           if(rs.next()){ /*Jika ada, maka akan dilanjutkan ke next*/
            HomePage a = new HomePage(); /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
            a.setVisible(true); /*Variabel tersebut akan menampilkan form yang dituju*/
            this.dispose(); /*Untuk menutup form*/
           }
           else{ /*Jika kondisi diatas tidak sesuai, maka menuju ke else*/
            NamaPenggunaEmail_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna or email yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang 
            telah dimasukkan dibuat menghilang*/
            KataSandi_TextField.setText(""); /*JTextField untuk menyimpan data kata sandi yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
            dibuat menghilang*/
            
            /*Memanggil ImageIcon dengan variabel yang tersedia pada file source pada packages pictures yang dimana 
            didalamnya terbagi menjadi beberapa file dan untuk memanggil ImageIcon yang ingin dipanggil*/
            ImageIcon NamaPenggunaTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
            NamaPenggunaTextField_icon = new ImageIcon("src/Pictures/LoginPage/Nama Pengguna Email Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
            NamaPenggunaEmail_Field.setIcon(NamaPenggunaTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
            ImageIcon KataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
            KataSandiTextField_icon = new ImageIcon("src/Pictures/LoginPage/Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
            KataSandi_Field.setIcon(KataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
            ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
            NotifFalse_icon = new ImageIcon("src/Pictures/LoginPage/Notif False Keduanya Salah.png"); /*Format pemanggilan file 
            ImageIcon yang ingin dipanggil*/
            KeduanyaSalah_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
            KeduanyaSalah_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
           
           }
        }
        catch(Exception e) /*Menangkap kesalahan atau bug yang terjadi dalam block try*/
        {
        JOptionPane.showMessageDialog(null, e); /*Kondisi apabila terjadi kesalahan pada saat melakukan input data*/
        }
    }//GEN-LAST:event_Masuk_TombolMouseClicked

    private void Masuk_TombolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_TombolMouseEntered
        ImageIcon MasukTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MasukTombol_icon = new ImageIcon("src/Pictures/LoginPage/Tombol Masuk 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Masuk_Tombol.setIcon(MasukTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Masuk_TombolMouseEntered

    private void Masuk_TombolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_TombolMouseExited
        ImageIcon MasukTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MasukTombol_icon = new ImageIcon("src/Pictures/LoginPage/Tombol Masuk 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Masuk_Tombol.setIcon(MasukTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Masuk_TombolMouseExited

    private void Masuk_TombolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_TombolMousePressed
        ImageIcon MasukTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MasukTombol_icon = new ImageIcon("src/Pictures/LoginPage/Tombol Masuk 4.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Masuk_Tombol.setIcon(MasukTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Masuk_TombolMousePressed

    private void Masuk_TombolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Masuk_TombolMouseReleased
        ImageIcon MasukTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        MasukTombol_icon = new ImageIcon("src/Pictures/LoginPage/Tombol Masuk 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Masuk_Tombol.setIcon(MasukTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Masuk_TombolMouseReleased

    private void LupaKataSandi_KlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LupaKataSandi_KlikMouseClicked
        ImageIcon LupaKataSandiKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        LupaKataSandiKlik_icon = new ImageIcon("src/Pictures/LoginPage/Lupa kata sandi 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        LupaKataSandi_Klik.setIcon(LupaKataSandiKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        LupaKataSandiPage x = new LupaKataSandiPage(); /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        x.setVisible(true); /*Variabel tersebut akan menampilkan form yang dituju*/
        this.dispose(); /*Untuk menutup form*/
    }//GEN-LAST:event_LupaKataSandi_KlikMouseClicked

    private void LupaKataSandi_KlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LupaKataSandi_KlikMouseEntered
        ImageIcon LupaKataSandiKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        LupaKataSandiKlik_icon = new ImageIcon("src/Pictures/LoginPage/Lupa kata sandi 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        LupaKataSandi_Klik.setIcon(LupaKataSandiKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_LupaKataSandi_KlikMouseEntered

    private void LupaKataSandi_KlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LupaKataSandi_KlikMouseExited
        ImageIcon LupaKataSandiKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        LupaKataSandiKlik_icon = new ImageIcon("src/Pictures/LoginPage/Lupa kata sandi 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        LupaKataSandi_Klik.setIcon(LupaKataSandiKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_LupaKataSandi_KlikMouseExited

    private void LupaKataSandi_KlikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LupaKataSandi_KlikMousePressed
        ImageIcon LupaKataSandiKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        LupaKataSandiKlik_icon = new ImageIcon("src/Pictures/LoginPage/Lupa kata sandi 4.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        LupaKataSandi_Klik.setIcon(LupaKataSandiKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_LupaKataSandi_KlikMousePressed

    private void LupaKataSandi_KlikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LupaKataSandi_KlikMouseReleased
        ImageIcon LupaKataSandiKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        LupaKataSandiKlik_icon = new ImageIcon("src/Pictures/LoginPage/Lupa kata sandi 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        LupaKataSandi_Klik.setIcon(LupaKataSandiKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_LupaKataSandi_KlikMouseReleased

    private void Daftar_KlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_KlikMouseClicked
        ImageIcon DaftarKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        DaftarKlik_icon = new ImageIcon("src/Pictures/LoginPage/Daftar 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Klik.setIcon(DaftarKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        SignUpPage x = new SignUpPage(); /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        x.setVisible(true); /*Variabel tersebut akan menampilkan form yang dituju*/
        this.dispose(); /*Untuk menutup form*/
    }//GEN-LAST:event_Daftar_KlikMouseClicked

    private void Daftar_KlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_KlikMouseEntered
        ImageIcon DaftarKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        DaftarKlik_icon = new ImageIcon("src/Pictures/LoginPage/Daftar 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Klik.setIcon(DaftarKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_KlikMouseEntered

    private void Daftar_KlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_KlikMouseExited
        ImageIcon DaftarKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        DaftarKlik_icon = new ImageIcon("src/Pictures/LoginPage/Daftar 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Klik.setIcon(DaftarKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_KlikMouseExited

    private void Daftar_KlikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_KlikMousePressed
        ImageIcon DaftarKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        DaftarKlik_icon = new ImageIcon("src/Pictures/LoginPage/Daftar 4.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Klik.setIcon(DaftarKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_KlikMousePressed

    private void Daftar_KlikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_KlikMouseReleased
        ImageIcon DaftarKlik_icon; /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
        DaftarKlik_icon = new ImageIcon("src/Pictures/LoginPage/Daftar 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Klik.setIcon(DaftarKlik_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_KlikMouseReleased

    private void MataTutup_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataTutup_IconMouseClicked
        ImageIcon MataTutup_icon;
        MataTutup_icon = new ImageIcon("src/Pictures/LoginPage/Mata Tutup.png");
        MataTutup_Icon.setIcon(MataTutup_icon);
        
        KataSandi_TextField.setEchoChar('\u25cf');
    }//GEN-LAST:event_MataTutup_IconMouseClicked

    private void MataTutup_IconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataTutup_IconMousePressed
        ImageIcon MataBuka_icon;
        MataBuka_icon = new ImageIcon("src/Pictures/LoginPage/Mata Buka.png");
        MataTutup_Icon.setIcon(MataBuka_icon);
        
        KataSandi_TextField.setEchoChar((char)0);
    }//GEN-LAST:event_MataTutup_IconMousePressed

    private void KataSandi_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KataSandi_TextFieldFocusGained
        KataSandi_Text.setVisible(false);
    }//GEN-LAST:event_KataSandi_TextFieldFocusGained

    private void KataSandi_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KataSandi_TextFieldFocusLost
        if(KataSandi_TextField.getText().length() == 0){
             KataSandi_Text.setVisible(true);
        }
    }//GEN-LAST:event_KataSandi_TextFieldFocusLost

    private void KataSandi_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KataSandi_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            NamaPenggunaEmail_TextField.requestFocus();
       }
    }//GEN-LAST:event_KataSandi_TextFieldKeyPressed

    private void NamaPenggunaEmail_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaPenggunaEmail_TextFieldFocusGained
        NamaPenggunaEmail_Text.setVisible(false);
    }//GEN-LAST:event_NamaPenggunaEmail_TextFieldFocusGained

    private void NamaPenggunaEmail_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaPenggunaEmail_TextFieldFocusLost
        if(NamaPenggunaEmail_TextField.getText().length() == 0){
             NamaPenggunaEmail_Text.setVisible(true);
        }
    }//GEN-LAST:event_NamaPenggunaEmail_TextFieldFocusLost

    private void NamaPenggunaEmail_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaPenggunaEmail_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            KataSandi_TextField.requestFocus();
       }else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            KataSandi_TextField.requestFocus();
        }
    }//GEN-LAST:event_NamaPenggunaEmail_TextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Daftar_Klik;
    private javax.swing.JLabel KataSandi_Field;
    private javax.swing.JLabel KataSandi_Text;
    private javax.swing.JPasswordField KataSandi_TextField;
    private javax.swing.JLabel KeduanyaSalah_NotifFalse;
    private javax.swing.JLabel Latar_Picture;
    private javax.swing.JLabel Login_Picture;
    private javax.swing.JLabel Logo_Picture;
    private javax.swing.JLabel LupaKataSandi_Klik;
    private javax.swing.JLabel Masuk_Tombol;
    private javax.swing.JLabel MataTutup_Icon;
    private javax.swing.JLabel NamaPenggunaEmail_Field;
    private javax.swing.JLabel NamaPenggunaEmail_Text;
    private javax.swing.JTextField NamaPenggunaEmail_TextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
