/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author iwaya
 */
public class LupaKataSandiPage extends javax.swing.JFrame {
        
    /**
     * Creates new form LupaKataSandiPage
     */
    public LupaKataSandiPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        NamaPenggunaEmail_TextField.setBackground(new java.awt.Color(0,0,0,1));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo_Picture = new javax.swing.JLabel();
        Latar_Picture = new javax.swing.JLabel();
        NamaPenggunaEmail_Text = new javax.swing.JLabel();
        NamaPenggunaEmail_TextField = new javax.swing.JTextField();
        NamaPenggunaEmail_Field = new javax.swing.JLabel();
        NamaPenggunaEmail_NotifFalse = new javax.swing.JLabel();
        Lanjut_Tombol = new javax.swing.JLabel();
        LupaKataSandi_Picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 57, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LupaKataSandiPage/Logo.png"))); // NOI18N
        jPanel1.add(Logo_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 82, -1, -1));

        Latar_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LupaKataSandiPage/Gambar Latar.png"))); // NOI18N
        jPanel1.add(Latar_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 26, -1, -1));

        NamaPenggunaEmail_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LupaKataSandiPage/Nama Pengguna atau Email.png"))); // NOI18N
        jPanel1.add(NamaPenggunaEmail_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 522, -1, -1));

        NamaPenggunaEmail_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        NamaPenggunaEmail_TextField.setForeground(new java.awt.Color(255, 255, 255));
        NamaPenggunaEmail_TextField.setBorder(null);
        NamaPenggunaEmail_TextField.setOpaque(false);
        NamaPenggunaEmail_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NamaPenggunaEmail_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NamaPenggunaEmail_TextFieldFocusLost(evt);
            }
        });
        jPanel1.add(NamaPenggunaEmail_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 515, 330, 30));

        NamaPenggunaEmail_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LupaKataSandiPage/Nama Pengguna Email Field.png"))); // NOI18N
        jPanel1.add(NamaPenggunaEmail_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1231, 498, -1, -1));
        jPanel1.add(NamaPenggunaEmail_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 590, -1, -1));

        Lanjut_Tombol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LupaKataSandiPage/Tombol Lanjut 1.png"))); // NOI18N
        Lanjut_Tombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lanjut_TombolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lanjut_TombolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lanjut_TombolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lanjut_TombolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Lanjut_TombolMouseReleased(evt);
            }
        });
        jPanel1.add(Lanjut_Tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 666, -1, -1));

        LupaKataSandi_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LupaKataSandiPage/Lupa Kata Sandi.png"))); // NOI18N
        jPanel1.add(LupaKataSandi_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1132, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaPenggunaEmail_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaPenggunaEmail_TextFieldFocusGained
        NamaPenggunaEmail_Text.setVisible(false);
    }//GEN-LAST:event_NamaPenggunaEmail_TextFieldFocusGained

    private void NamaPenggunaEmail_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaPenggunaEmail_TextFieldFocusLost
        if(NamaPenggunaEmail_TextField.getText().length() == 0){
            NamaPenggunaEmail_Text.setVisible(true);
        }
    }//GEN-LAST:event_NamaPenggunaEmail_TextFieldFocusLost

    private void Lanjut_TombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lanjut_TombolMouseClicked
        ImageIcon LanjutTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        LanjutTombol_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Tombol Lanjut 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Lanjut_Tombol.setIcon(LanjutTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        String NamaPenggunaEmail = NamaPenggunaEmail_TextField.getText(); /*Variabel untuk mengambil data Username atau Email*/
        
        /*Try dan Catch digunakan untuk menangani error pada java, eksekusi yang menampilkan 
        error dan membuat program tetap berjalan tanpa dihentikan secara langsung*/
        try{ /*Statement yang digunakan untuk menghubungkan database pada mysql ke Netbeans*/
           Class.forName("com.mysql.jdbc.Driver"); /*Pemanggilan kelas pad library JDBC driver mysql*/
           Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coba","root", ""); /*variabel yang digunakan untuk pemanggilan driver mysql pada database server*/
           String sql = "select * from tb_daftar where nama=? Or email=?"; /*Syntax pada mysql yang digunakan untuk melakukan pemasukkan data username atau email ke tb_signin*/
           PreparedStatement pst = connect.prepareStatement(sql); /*Variabel untuk mengambil data-data yang ingin dimasukkan ke dalam database server*/
           pst.setString(1, NamaPenggunaEmail_TextField.getText()); /*Pemasangan dan pemasukkan data username pada database server*/
           pst.setString(2, NamaPenggunaEmail_TextField.getText()); /*Pemasangan dan pemasukkan data email pada database server*/
           ResultSet rs = pst.executeQuery(); /*Memeriksa apakah ada hasil yang dimasukkan*/
           
           if(rs.next()){ /*Jika ada, maka akan dilanjutkan ke next*/
            new KataSandiBaruPage(NamaPenggunaEmail).setVisible(true); /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju */
            setVisible(false); /*Membuat JLabel menghilang pada JTextField*/
           }
           else{ /*Jika kondisi diatas tidak sesuai, maka menuju ke else*/
            NamaPenggunaEmail_TextField.setText("");/*JTextField untuk menyimpan data username atau email yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah 
            dimasukkan di buat menghilang*/
        
            ImageIcon NamaPenggunaTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
            NamaPenggunaTextField_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Nama Pengguna Email Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
            NamaPenggunaEmail_Field.setIcon(NamaPenggunaTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
            ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
            NotifFalse_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Notif False Keduanya Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
            NamaPenggunaEmail_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
            NamaPenggunaEmail_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
           }
        }
        catch(Exception e) /*Menangkap kesalahan atau bug yang terjadi dalam block try*/
        {
        JOptionPane.showMessageDialog(null, e); /*Kondisi apabila terjadi kesalahan pada saat melakukan input data*/
        }
    }//GEN-LAST:event_Lanjut_TombolMouseClicked

    private void Lanjut_TombolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lanjut_TombolMouseEntered
        ImageIcon LanjutTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        LanjutTombol_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Tombol Lanjut 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Lanjut_Tombol.setIcon(LanjutTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Lanjut_TombolMouseEntered

    private void Lanjut_TombolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lanjut_TombolMouseExited
        ImageIcon LanjutTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        LanjutTombol_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Tombol Lanjut 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Lanjut_Tombol.setIcon(LanjutTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Lanjut_TombolMouseExited

    private void Lanjut_TombolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lanjut_TombolMousePressed
        ImageIcon LanjutTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        LanjutTombol_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Tombol Lanjut 4.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Lanjut_Tombol.setIcon(LanjutTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Lanjut_TombolMousePressed

    private void Lanjut_TombolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lanjut_TombolMouseReleased
        ImageIcon LanjutTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        LanjutTombol_icon = new ImageIcon("src/Pictures/LupaKataSandiPage/Tombol Lanjut 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Lanjut_Tombol.setIcon(LanjutTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Lanjut_TombolMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaKataSandiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaKataSandiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaKataSandiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaKataSandiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaKataSandiPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lanjut_Tombol;
    private javax.swing.JLabel Latar_Picture;
    private javax.swing.JLabel Logo_Picture;
    private javax.swing.JLabel LupaKataSandi_Picture;
    private javax.swing.JLabel NamaPenggunaEmail_Field;
    private javax.swing.JLabel NamaPenggunaEmail_NotifFalse;
    private javax.swing.JLabel NamaPenggunaEmail_Text;
    private javax.swing.JTextField NamaPenggunaEmail_TextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
