/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author iwaya
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        NamaPengguna_TextField.setBackground(new java.awt.Color(0,0,0,1));
        Email_TextField.setBackground(new java.awt.Color(0,0,0,1));
        KataSandi_TextField.setBackground(new java.awt.Color(0,0,0,1));
        KonfirmasiKataSandi_TextField.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo_Picture = new javax.swing.JLabel();
        Latar_Picture = new javax.swing.JLabel();
        NamaPengguna_Text = new javax.swing.JLabel();
        NamaPengguna_TextField = new javax.swing.JTextField();
        NamaPengguna_Field = new javax.swing.JLabel();
        NamaPengguna_NotifFalse = new javax.swing.JLabel();
        Email_Text = new javax.swing.JLabel();
        Email_TextField = new javax.swing.JTextField();
        Email_Field = new javax.swing.JLabel();
        Email_NotifFalse = new javax.swing.JLabel();
        KataSandi_Text = new javax.swing.JLabel();
        KataSandi_TextField = new javax.swing.JPasswordField();
        MataTutup1_Icon = new javax.swing.JLabel();
        KataSandi_Field = new javax.swing.JLabel();
        KataSandi_NotifFalse = new javax.swing.JLabel();
        KonfirmasiKataSandi_Text = new javax.swing.JLabel();
        KonfirmasiKataSandi_TextField = new javax.swing.JPasswordField();
        MataTutup2_Icon = new javax.swing.JLabel();
        KonfirmasiKataSandi_Field = new javax.swing.JLabel();
        KonfirmasiKataSandi_NotifFalse = new javax.swing.JLabel();
        Daftar_Tombol = new javax.swing.JLabel();
        SemuaSalah_NotifFalse = new javax.swing.JLabel();
        SignUp_Picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 57, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Logo.png"))); // NOI18N
        jPanel1.add(Logo_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 95, -1, -1));

        Latar_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Gambar Latar.png"))); // NOI18N
        jPanel1.add(Latar_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 424, -1, -1));

        NamaPengguna_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Nama Pengguna.png"))); // NOI18N
        jPanel1.add(NamaPengguna_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 320, -1, -1));

        NamaPengguna_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        NamaPengguna_TextField.setForeground(new java.awt.Color(255, 255, 255));
        NamaPengguna_TextField.setBorder(null);
        NamaPengguna_TextField.setOpaque(false);
        NamaPengguna_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NamaPengguna_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NamaPengguna_TextFieldFocusLost(evt);
            }
        });
        NamaPengguna_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaPengguna_TextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(NamaPengguna_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 315, 330, 30));

        NamaPengguna_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Nama Pengguna Field.png"))); // NOI18N
        jPanel1.add(NamaPengguna_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1231, 296, -1, -1));
        jPanel1.add(NamaPengguna_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 385, -1, -1));

        Email_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Email.png"))); // NOI18N
        jPanel1.add(Email_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 465, -1, -1));

        Email_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Email_TextField.setForeground(new java.awt.Color(255, 255, 255));
        Email_TextField.setBorder(null);
        Email_TextField.setOpaque(false);
        Email_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_TextFieldFocusLost(evt);
            }
        });
        Email_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Email_TextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 455, 330, 30));

        Email_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Email Field.png"))); // NOI18N
        jPanel1.add(Email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1231, 439, -1, -1));
        jPanel1.add(Email_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 528, -1, -1));

        KataSandi_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Kata Sandi.png"))); // NOI18N
        jPanel1.add(KataSandi_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 613, -1, -1));

        KataSandi_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        KataSandi_TextField.setForeground(new java.awt.Color(255, 255, 255));
        KataSandi_TextField.setBorder(null);
        KataSandi_TextField.setEchoChar('\u25cf');
        KataSandi_TextField.setOpaque(false);
        KataSandi_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KataSandi_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KataSandi_TextFieldFocusLost(evt);
            }
        });
        KataSandi_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KataSandi_TextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(KataSandi_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 605, 300, 30));

        MataTutup1_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Mata Tutup.png"))); // NOI18N
        MataTutup1_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MataTutup1_IconMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MataTutup1_IconMousePressed(evt);
            }
        });
        jPanel1.add(MataTutup1_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1613, 607, -1, -1));

        KataSandi_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Kata Sandi Field.png"))); // NOI18N
        jPanel1.add(KataSandi_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1231, 585, -1, -1));
        jPanel1.add(KataSandi_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 677, -1, -1));

        KonfirmasiKataSandi_Text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Konfirmasi Kata Sandi.png"))); // NOI18N
        jPanel1.add(KonfirmasiKataSandi_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 761, -1, -1));

        KonfirmasiKataSandi_TextField.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        KonfirmasiKataSandi_TextField.setForeground(new java.awt.Color(255, 255, 255));
        KonfirmasiKataSandi_TextField.setBorder(null);
        KonfirmasiKataSandi_TextField.setEchoChar('\u25cf');
        KonfirmasiKataSandi_TextField.setOpaque(false);
        KonfirmasiKataSandi_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KonfirmasiKataSandi_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KonfirmasiKataSandi_TextFieldFocusLost(evt);
            }
        });
        KonfirmasiKataSandi_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KonfirmasiKataSandi_TextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(KonfirmasiKataSandi_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 755, 300, 30));

        MataTutup2_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Mata Tutup.png"))); // NOI18N
        MataTutup2_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MataTutup2_IconMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MataTutup2_IconMousePressed(evt);
            }
        });
        jPanel1.add(MataTutup2_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1613, 755, -1, -1));

        KonfirmasiKataSandi_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Konfirmasi Kata Sandi Field.png"))); // NOI18N
        jPanel1.add(KonfirmasiKataSandi_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1231, 733, -1, -1));
        jPanel1.add(KonfirmasiKataSandi_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 825, -1, -1));

        Daftar_Tombol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Tombol Daftar 1.png"))); // NOI18N
        Daftar_Tombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Daftar_TombolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Daftar_TombolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Daftar_TombolMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Daftar_TombolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Daftar_TombolMouseReleased(evt);
            }
        });
        jPanel1.add(Daftar_Tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 872, -1, -1));
        jPanel1.add(SemuaSalah_NotifFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 825, -1, -1));

        SignUp_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/SignUpPage/Sign Up.png"))); // NOI18N
        jPanel1.add(SignUp_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaPengguna_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaPengguna_TextFieldFocusGained
        NamaPengguna_Text.setVisible(false);
    }//GEN-LAST:event_NamaPengguna_TextFieldFocusGained

    private void NamaPengguna_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaPengguna_TextFieldFocusLost
        if(NamaPengguna_TextField.getText().length() == 0){
            NamaPengguna_Text.setVisible(true);
        }
    }//GEN-LAST:event_NamaPengguna_TextFieldFocusLost

    private void NamaPengguna_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaPengguna_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            Email_TextField.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Email_TextField.requestFocus();
        }
    }//GEN-LAST:event_NamaPengguna_TextFieldKeyPressed

    private void Email_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TextFieldFocusGained
        Email_Text.setVisible(false);
    }//GEN-LAST:event_Email_TextFieldFocusGained

    private void Email_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TextFieldFocusLost
        if(Email_TextField.getText().length() == 0){
            Email_Text.setVisible(true);
        }
    }//GEN-LAST:event_Email_TextFieldFocusLost

    private void Email_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Email_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            KataSandi_TextField.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            KataSandi_TextField.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_UP){
            NamaPengguna_TextField.requestFocus();
        }
    }//GEN-LAST:event_Email_TextFieldKeyPressed

    private void KataSandi_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KataSandi_TextFieldFocusGained
        KataSandi_Text.setVisible(false);
    }//GEN-LAST:event_KataSandi_TextFieldFocusGained

    private void KataSandi_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KataSandi_TextFieldFocusLost
        if(KataSandi_TextField.getText().length() == 0){
            KataSandi_Text.setVisible(true);
        }
    }//GEN-LAST:event_KataSandi_TextFieldFocusLost

    private void KataSandi_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KataSandi_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            KonfirmasiKataSandi_TextField.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            KonfirmasiKataSandi_TextField.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_UP){
            Email_TextField.requestFocus();
        }
    }//GEN-LAST:event_KataSandi_TextFieldKeyPressed

    private void MataTutup1_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataTutup1_IconMouseClicked
        ImageIcon MataTutup1_icon;
        MataTutup1_icon = new ImageIcon("src/Pictures/SignUpPage/Mata Tutup.png");
        MataTutup1_Icon.setIcon(MataTutup1_icon);

        KataSandi_TextField.setEchoChar('\u25cf');
    }//GEN-LAST:event_MataTutup1_IconMouseClicked

    private void MataTutup1_IconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataTutup1_IconMousePressed
        ImageIcon MataBuka_icon;
        MataBuka_icon = new ImageIcon("src/Pictures/SignUpPage/Mata Buka.png");
        MataTutup1_Icon.setIcon(MataBuka_icon);

        KataSandi_TextField.setEchoChar((char)0);
    }//GEN-LAST:event_MataTutup1_IconMousePressed

    private void MataTutup2_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataTutup2_IconMouseClicked
        ImageIcon MataTutup2_icon;
        MataTutup2_icon = new ImageIcon("src/Pictures/SignUpPage/Mata Tutup.png");
        MataTutup2_Icon.setIcon(MataTutup2_icon);

        KonfirmasiKataSandi_TextField.setEchoChar('\u25cf');
    }//GEN-LAST:event_MataTutup2_IconMouseClicked

    private void MataTutup2_IconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MataTutup2_IconMousePressed
        ImageIcon MataBuka_icon;
        MataBuka_icon = new ImageIcon("src/Pictures/SignUpPage/Mata Buka.png");
        MataTutup2_Icon.setIcon(MataBuka_icon);

        KonfirmasiKataSandi_TextField.setEchoChar((char)0);
    }//GEN-LAST:event_MataTutup2_IconMousePressed

    private void KonfirmasiKataSandi_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KonfirmasiKataSandi_TextFieldFocusGained
        KonfirmasiKataSandi_Text.setVisible(false);
    }//GEN-LAST:event_KonfirmasiKataSandi_TextFieldFocusGained

    private void KonfirmasiKataSandi_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KonfirmasiKataSandi_TextFieldFocusLost
        if(KonfirmasiKataSandi_TextField.getText().length() == 0){
            KonfirmasiKataSandi_Text.setVisible(true);
        }
    }//GEN-LAST:event_KonfirmasiKataSandi_TextFieldFocusLost

    private void KonfirmasiKataSandi_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KonfirmasiKataSandi_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            KataSandi_TextField.requestFocus();
        }
    }//GEN-LAST:event_KonfirmasiKataSandi_TextFieldKeyPressed

    private void Daftar_TombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_TombolMouseClicked
        /*Memanggil ImageIcon dengan variabel DaftarTombol_icon pada file 
        source packages pictures yang dimana di dalamnya terbagi menjadi 
        beberapa file dan untuk memanggil ImageIcon yang ingin dipanggil*/
        ImageIcon DaftarTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        DaftarTombol_icon = new ImageIcon("src/Pictures/SignUpPage/Tombol Daftar 3.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Tombol.setIcon(DaftarTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
        
        /*Deklarasi variabel untuk melakukan pemasukkan data pada mysql*/
        String NamaPengguna = NamaPengguna_TextField.getText(); /*Variabel untuk mengambil data Nama Pengguna*/
        String Email = Email_TextField.getText(); /*Variabel untuk mengambil data Email*/
        String KataSandi = KataSandi_TextField.getPassword().toString(); /*Variabel untuk mengambil data Kata Sandi*/
        String KonfirmasiKataSandi = KonfirmasiKataSandi_TextField.getPassword().toString(); /*Variabel untuk mengambil data Konfirmasi Kata Sandi*/
        
        /*Try dan Catch digunakan untuk menangani error pada java, eksekusi yang menampilkan 
        error dan membuat program tetap berjalan tanpa dihentikan secara langsung*/
        try{ /*Statement yang digunakan untuk menghubungkan database pada mysql ke Netbeans*/
           Class.forName("com.mysql.jdbc.Driver"); /*Pemanggilan kelas pad library JDBC driver mysql*/
           Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coba","root", ""); /*variabel yang digunakan untuk pemanggilan driver mysql pada database server*/
           String sql = "insert into tb_daftar(nama,email,katasandi) values(?,?,?)"; /*Syntax pada mysql yang digunakan untuk melakukan pemasukkan data username dan password*/
           PreparedStatement pst = connect.prepareStatement(sql); /*Variabel untuk mengambil data-data yang ingin dimasukkan ke dalam database server*/
           pst.setString(1, NamaPengguna_TextField.getText()); /*Pemasangan dan pemasukkan data nama pengguna pada database server*/
           pst.setString(2, Email_TextField.getText()); /*Pemasangan dan pemasukkan data email pada database server*/
           pst.setString(3, KataSandi_TextField.getText()); /*Pemasangan dan pemasukkan data kata sandi pada database server*/
         
           if(NamaPengguna_TextField.getText().length()>0 && Email_TextField.getText().length()>0 && KataSandi_TextField.getPassword().length>0 && KataSandi_TextField.getText().equalsIgnoreCase(KonfirmasiKataSandi_TextField.getText())){  
               /*Kondisi bahwa karakter dari nama pengguna serta email yang telah dimasukkan pada JTextField haruslah kurang dari 101 karakter dan
               karakter dari kata sandi yang telah dimasukkan pada JTextField haruslah kurang dari 11 karakter*/
               pst.executeUpdate(); /*Untuk melakukan ekseskusi pada syntax sql*/
               KonfirmasiPage a = new KonfirmasiPage(); /*Deklarasi variabel pada form yang ingin dituju dan variabel tersebut menunjukkan nilai yang sama dengan form yang ingin dituju*/
               a.setVisible(true); /*Variabel tersebut akan menampilkan form yang dituju*/
               this.dispose(); /*Untuk menutup form*/
           }else if(NamaPengguna_TextField.getText().length() <= 0 && Email_TextField.getText().length() <= 0 && KataSandi_TextField.getPassword().length <= 0 && KonfirmasiKataSandi_TextField.getPassword().length <= 0){
               NamaPengguna_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon NamaPenggunaTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NamaPenggunaTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Nama Pengguna Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               NamaPengguna_Field.setIcon(NamaPenggunaTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               Email_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon EmailTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               EmailTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Email Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               Email_Field.setIcon(EmailTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               KataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon KataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               KataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KataSandi_Field.setIcon(KataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               KonfirmasiKataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon KonfirmasiKataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               KonfirmasiKataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Konfirmasi Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KonfirmasiKataSandi_Field.setIcon(KonfirmasiKataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Semua Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               SemuaSalah_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               SemuaSalah_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
            }else if(NamaPengguna_TextField.getText().length() == 0 || Email_TextField.getText().length() == 0 || KataSandi_TextField.getPassword().length == 0 || KonfirmasiKataSandi_TextField.getPassword().length == 0){
               
               SemuaSalah_NotifFalse.setVisible(false);
                
                if(NamaPengguna_TextField.getText().length() == 0){
                   
                   SemuaSalah_NotifFalse.setVisible(false);
                    
                   ImageIcon NamaPenggunaTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   NamaPenggunaTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Nama Pengguna Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   NamaPengguna_Field.setIcon(NamaPenggunaTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
                   ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Tidak Boleh Kosong.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   NamaPengguna_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
                   NamaPengguna_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
                   
                   if(NamaPengguna_TextField.getText().length() >= 0){
                   
                   SemuaSalah_NotifFalse.setVisible(false);
                    
                   ImageIcon NamaPenggunaTextField1_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   NamaPenggunaTextField1_icon = new ImageIcon("src/Pictures/SignUpPage/Nama Pengguna Field.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   NamaPengguna_Field.setIcon(NamaPenggunaTextField1_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
                   }
         
               }if(Email_TextField.getText().length() == 0){
                   
                   SemuaSalah_NotifFalse.setVisible(false);
                   
                   ImageIcon EmailTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   EmailTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Email Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   Email_Field.setIcon(EmailTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
                   ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Tidak Boleh Kosong.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   Email_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
                   Email_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
                
               }if(KataSandi_TextField.getPassword().length == 0){
                   
                   SemuaSalah_NotifFalse.setVisible(false);
                   
                   ImageIcon KataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   KataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   KataSandi_Field.setIcon(KataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
                   ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Tidak Boleh Kosong.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   KataSandi_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
                   KataSandi_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
               }if(KonfirmasiKataSandi_TextField.getPassword().length == 0){
                   
                   SemuaSalah_NotifFalse.setVisible(false);
                   
                   ImageIcon KonfirmasiKataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   KonfirmasiKataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Konfirmasi Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   KonfirmasiKataSandi_Field.setIcon(KonfirmasiKataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
                   ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
                   NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Tidak Boleh Kosong.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
                   KonfirmasiKataSandi_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
                   KonfirmasiKataSandi_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
               }
            }else if(NamaPengguna_TextField.getText().length() > 100){
               NamaPengguna_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               
               ImageIcon NamaPenggunaTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NamaPenggunaTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Nama Pengguna Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               NamaPengguna_Field.setIcon(NamaPenggunaTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Nama Pengguna.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               NamaPengguna_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               NamaPengguna_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
           }else if(Email_TextField.getText().length() > 100){
               Email_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               
               ImageIcon EmailTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               EmailTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Email Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               Email_Field.setIcon(EmailTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Email.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               Email_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               Email_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
           }else if(KataSandi_TextField.getPassword().length > 10 && KonfirmasiKataSandi_TextField.getPassword().length > 10 && KataSandi.equals(KonfirmasiKataSandi) == true){
               KonfirmasiKataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               KataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               
               KonfirmasiKataSandi_NotifFalse.setVisible(false);
               
               ImageIcon KataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               KataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KataSandi_Field.setIcon(KataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Kata Sandi.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KataSandi_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               KataSandi_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
           }else if(KataSandi.equals(KonfirmasiKataSandi) == false){
               KonfirmasiKataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               
               KataSandi_NotifFalse.setVisible(false);
               
               ImageIcon KonfirmasiKataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               KonfirmasiKataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Konfirmasi Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KonfirmasiKataSandi_Field.setIcon(KonfirmasiKataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Konfirmasi Kata Sandi.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KonfirmasiKataSandi_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               KonfirmasiKataSandi_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
            }else{
               NamaPengguna_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon NamaPenggunaTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NamaPenggunaTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Nama Pengguna Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               NamaPengguna_Field.setIcon(NamaPenggunaTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               Email_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon EmailTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               EmailTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Email Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               Email_Field.setIcon(EmailTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               KataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon KataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               KataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KataSandi_Field.setIcon(KataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               KonfirmasiKataSandi_TextField.setText(""); /*JTextField untuk menyimpan data nama pengguna yang dimana karakter kata yang telah dimasukkan yang dimana karakter kata yang telah dimasukkan 
               di buat menghilang*/
               ImageIcon KonfirmasiKataSandiTextField_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               KonfirmasiKataSandiTextField_icon = new ImageIcon("src/Pictures/SignUpPage/Konfirmasi Kata Sandi Field Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               KonfirmasiKataSandi_Field.setIcon(KonfirmasiKataSandiTextField_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               
               ImageIcon NotifFalse_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
               NotifFalse_icon = new ImageIcon("src/Pictures/SignUpPage/Notif False Semua Salah.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
               SemuaSalah_NotifFalse.setIcon(NotifFalse_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
               SemuaSalah_NotifFalse.setVisible(true); /*Membuat Jlabel muncul*/
            }
        }
        catch(ClassNotFoundException | SQLException e) /*Menangkap kesalahan atau bug yang terjadi dalam block try*/
        {
            if(KataSandi_TextField.getPassword().length > 10 && KonfirmasiKataSandi_TextField.getPassword().length > 10 && KataSandi.equals(KonfirmasiKataSandi) == true || KataSandi.equals(KonfirmasiKataSandi) == false){
                JOptionPane.showMessageDialog(this, "Kata sandi tidak lebih dari 10 karakter");
            }else{
            JOptionPane.showMessageDialog(null, e); /*Kondisi apabila terjadi kesalahan pada saat melakukan input data*/
            }
        }
    }//GEN-LAST:event_Daftar_TombolMouseClicked

    private void Daftar_TombolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_TombolMouseEntered
        ImageIcon DaftarTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        DaftarTombol_icon = new ImageIcon("src/Pictures/SignUpPage/Tombol Daftar 2.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Tombol.setIcon(DaftarTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_TombolMouseEntered

    private void Daftar_TombolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_TombolMouseExited
        ImageIcon DaftarTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        DaftarTombol_icon = new ImageIcon("src/Pictures/SignUpPage/Tombol Daftar 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Tombol.setIcon(DaftarTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_TombolMouseExited

    private void Daftar_TombolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_TombolMousePressed
        ImageIcon DaftarTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        DaftarTombol_icon = new ImageIcon("src/Pictures/SignUpPage/Tombol Daftar 4.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Tombol.setIcon(DaftarTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_TombolMousePressed

    private void Daftar_TombolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daftar_TombolMouseReleased
        ImageIcon DaftarTombol_icon; /*Deklarasi variabel yang digunakan untuk memanggil ImageIcon*/
        DaftarTombol_icon = new ImageIcon("src/Pictures/SignUpPage/Tombol Daftar 1.png"); /*Format pemanggilan file ImageIcon yang ingin dipanggil*/
        Daftar_Tombol.setIcon(DaftarTombol_icon); /*Pallete pada java (berupa JLabel) yang digunakan untuk melakukan set pada ImageIcon*/
    }//GEN-LAST:event_Daftar_TombolMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Daftar_Tombol;
    private javax.swing.JLabel Email_Field;
    private javax.swing.JLabel Email_NotifFalse;
    private javax.swing.JLabel Email_Text;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JLabel KataSandi_Field;
    private javax.swing.JLabel KataSandi_NotifFalse;
    private javax.swing.JLabel KataSandi_Text;
    private javax.swing.JPasswordField KataSandi_TextField;
    private javax.swing.JLabel KonfirmasiKataSandi_Field;
    private javax.swing.JLabel KonfirmasiKataSandi_NotifFalse;
    private javax.swing.JLabel KonfirmasiKataSandi_Text;
    private javax.swing.JPasswordField KonfirmasiKataSandi_TextField;
    private javax.swing.JLabel Latar_Picture;
    private javax.swing.JLabel Logo_Picture;
    private javax.swing.JLabel MataTutup1_Icon;
    private javax.swing.JLabel MataTutup2_Icon;
    private javax.swing.JLabel NamaPengguna_Field;
    private javax.swing.JLabel NamaPengguna_NotifFalse;
    private javax.swing.JLabel NamaPengguna_Text;
    private javax.swing.JTextField NamaPengguna_TextField;
    private javax.swing.JLabel SemuaSalah_NotifFalse;
    private javax.swing.JLabel SignUp_Picture;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
